trigger:
- master

pool:
  name: 'MyAgent'

variables:
  buildConfiguration: 'Release'
  projectName: 'MyEcommerceBackend'
  webAppName: 'LearnHowToDev'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore
  displayName: 'Restore'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'

- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish
  displayName: 'Publish'

- powershell: |
    git clone https://github.com/JonathanHoward86/BackendDevProject.git temp
    $filesToMove = Get-ChildItem -Path temp -File
    foreach ($file in $filesToMove) {
        $targetPath = Join-Path -Path $(System.DefaultWorkingDirectory) -ChildPath $file.Name
        Move-Item -Path $file.FullName -Destination $targetPath -Force
    }
    Remove-Item -Path temp -Recurse -Force
  displayName: 'Pull code from GitHub'
  env:
    GITHUB_TOKEN: $(githubPat)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
    artifactName: 'drop'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(238bd2e9-c0c4-4f2e-ad95-3cb2d79eedfa)'
    appType: 'webApp'
    webAppName: $(webAppName)
    deployToSlotOrASE: true
    resourceGroupName: 'DefaultResourceGroup-CUS'
    slotName: 'production'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/publish'
